### ISSUE TITLE
Secure routes do not work any more.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift-labs/learn-katacoda#539]
Am pretty sure that secure routes did at one point work for applications deployed in the OpenShift cluster, and if my memory is correct and they did, they don't work anymore.

Consider doing the scenario:

* https://learn.openshift.com/introduction/deploying-images/

When you get to creating the route, in the web console page, select "Secure route".

This option would not normally be selected and would create only a `http` route. We want to select it though so have a `https` route. As is, with just that, both `http` and `https` routes should be allowed. That is, `http` will not be redirected to `https` by OpenShift as insecure traffic policy will be None (Allow), rather than redirect.

If you now go to the that URL, you end up stuck on the "Connecting to Port 80" page and can never get to the application.

You get the same problem if the insecure traffic policy is redirect.

**Comment by BenHall** [comment]
Thanks @GrahamDumpleton. This is something we had already fixed for 3.11 and it's been live for some time. I wasn't aware that 3.6 also had this. 

I've applied it to the infrastructure running 3.11 so if users do select secure, they it will work as expected. 

Could you expand on `insecure traffic policy`? I'm not sure how that is different?

**Comment by GrahamDumpleton** [comment]
Hmmm, it was actually 3.11 where I was having the problem. I checked 3.6 and it also had the problem, so was easier for me to use the 3.6 example to show the problem. I will check again with 3.11 again.

**Comment by BenHall** [comment]
Please let me know.

The only time I've come across it not loading recently is when http is used but the router is expecting https.

**Comment by GrahamDumpleton** [comment]
The other possibility is that the use of the proxy, or the proxy itself, plays games with the cookies being sent through. Trying again today, I have got one application to work, but another fails because it gets sent into a redirect loop.

**Comment by GrahamDumpleton** [comment]
Narrowed it down. Specifically relates to insecure traffic policy of redirect. This fails for `Route`:

```
spec:
  host: ""
  port:
    targetPort: 8080-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: workspace
    weight: 100
  wildcardPolicy: None
```

but this works:

```
spec:
  host: ""
  port:
    targetPort: 8080-tcp
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  to:
    kind: Service
    name: workspace
    weight: 100
  wildcardPolicy: None
```

The difference is `insecureEdgeTerminationPolicy`.

For `Redirect`, a request against `http` would be redirected by OpenShift to `https`. With `Allow`, you can connect on either `http` or `https` and no redirection from `http` to `https` occurs.

How does you proxy work? Is it going to handle OpenShift (or an application) responding with a redirect from `http` to `https`?
