### ISSUE TITLE
Support Serverless Routes

### ISSUE THREAD

**Issue by btannous** [openshift-labs/learn-katacoda#692]
Knative/OpenShift Serverless use a different route format than usual routes in OCP. I'm getting 502's from nginx (I believe on katacoda's side).
- Knative's URL format: `http://greeter.serverless-tutorial.2886795277-80-shadow01.environments.katacoda.com/`
- Standard OCP Route Format: `http://blog-django-py-myproject.2886795274-80-host04nc.environments.katacoda.com/`

To test:
- https://katacoda.com/btannous/courses/middleware/serverless
- Start scenario
- Wait until all pods from `oc get -n knative-serving pods` have a `status` of `running`
- `oc apply -n serverless-tutorial -f basics/service.yaml`
- Wait until `oc get -n serverless-tutorial services.serving.knative.dev` shows `ready = true`
- attempt to go to route, see **502** error.

Can also see error using the example app for serverless.
- Apply the yaml below:
```yaml
echo "apiVersion: serving.knative.dev/v1alpha1 
kind: Service
metadata:
  name: helloworld-go 
  namespace: default 
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-samples/helloworld-go 
          env:
            - name: TARGET 
              value: "Go Sample v1"
```
- `oc get -n default services.serving.knative.dev`
- head to route, see katacoda **waiting for port 80**?
